# Generated by Django 3.2.9 on 2021-11-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cotegory',
            field=models.CharField(choices=[('sad_sayeri', 'sad_sayeri'), ('love_sayeri', 'love_sayeri'), ('birthday_sayeri', 'birthday_sayeri'), ('heart_sayeri', 'heart_sayeri')], default='love_sayeri', max_length=100),
        ),
    ]
