# Generated by Django 3.2.9 on 2021-11-10 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog_app', '0005_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cotegory',
            field=models.CharField(choices=[('sad_sayeri', 'sad_sayeri'), ('love_sayeri', 'love_sayeri'), ('birthday_sayeri', 'birthday_sayeri'), ('heart_sayeri', 'heart_sayeri'), ('attitude_sayeri', 'attitude_sayeri')], default='love_sayeri', max_length=100),
        ),
        migrations.CreateModel(
            name='blogcomment',
            fields=[
                ('sn', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog_app.blogcomment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_app.post')),
                ('userc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
