# Generated by Django 3.2.9 on 2021-11-10 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0006_auto_20211110_1017'),
    ]

    operations = [
        migrations.DeleteModel(
            name='blogcomment',
        ),
    ]
