# Generated by Django 3.2.9 on 2021-11-11 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0010_bloglike'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bloglike',
        ),
    ]
