# Generated by Django 3.2.9 on 2021-11-12 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0014_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
